language: node_js
node_js:
  - "0.10"
before_install:
  - rvm install 2.1.1
  - rvm use 2.1.1
  - travis_retry npm install -g bower grunt-cli karma
install:
  - travis_retry npm install
  - travis_retry bower install
  - travis_retry bundle install
before_script:
  - grunt build
after_script:
  - grunt ftp-deploy

